name: kopa
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #STATE MANAGMENT
  get: ^4.6.5

  #FIREBASE PACKAGES
  cloud_firestore: ^3.4.4
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0

  #UI
  animated_splash_screen: ^1.3.0
  convex_bottom_bar: ^3.0.0
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.9
  flutter_svg: ^1.1.4
  google_fonts: ^3.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

#icon launcher
  flutter_launcher_icons: ^0.10.0
flutter_icons:
  androd: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/app_icon/ios_icon.png'
  adaptive_icon_foreground: 'assets/app_icon/android_icon.png'

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/vector/
    - assets/1x/
    - assets/2x/
    - assets/3x/
    - assets/app_icon/
    - assets/json/

